version: "3.3"
services:
  # Websites - 4000-4049
  web-rust-lang:
    image: web-rust-lang
    ports:
      - "4000:4000"
    environment:
      PORT: "4000"
    env_file:
      - .env
      - .env.local
    build:
      context: "."
      dockerfile: packages/web-rust-lang/Dockerfile
  web-crates-io:
    image: web-crates-io
    ports:
      - "4001:4001"
    environment:
      PORT: "4001"
    env_file:
      - .env
      - .env.local
    build:
      context: "."

      dockerfile: packages/web-crates-io/Dockerfile

  # Website Test harness UI - 4050-4099
  web-components:
    image: web-components
    ports:
      - "4050:4050"
    environment:
      PORT: "4050"
    env_file:
      - .env
      - .env.local
    build:
      context: "."
      dockerfile: packages/web-components/Dockerfile

  # API 8000-8049
  web-api-proxy:
    image: web-api-proxy
    ports:
      - "8000:8000"
    environment:
      PORT: "8000"
    env_file:
      - .env
      - .env.local
    build:
      context: "."
      dockerfile: packages/web-api-proxy/Dockerfile
