const { describe, test, expect } = require("@jest/globals");
const { fileMatchesTemplate } = require("./file-matches-template");

// prettier-ignore
const shouldFailFixtures = [
  ["/apple-touch-icon.png", "static/media/[name].[contenthash:8].[ext]"],
  ["/favicon-16x16.png", "static/media/[name].[contenthash:8].[ext]"],
  ["/favicon-32x32.png", "static/media/[name].[contenthash:8].[ext]"],
  ["/favicon.svg", "static/media/[name].[contenthash:8].[ext]"],
  ["/robots.txt", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/js/0.b188e5bb.chunk.js.LICENSE.txt", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/js/1.c8bc9647.chunk.js.LICENSE.txt", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/js/3.e1d0e2fa.chunk.js.LICENSE.txt", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/js/4.1617d2d8.chunk.js.LICENSE.txt", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/js/5.a7fdfab7.chunk.js.LICENSE.txt", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/js/6.997a26e3.chunk.js.LICENSE.txt", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/js/7.8e1edd37.chunk.js.LICENSE.txt", "static/media/[name].[contenthash:8].[ext]"],
];

// prettier-ignore
const shouldPassFixtures = [
  ["/static/js/0.b188e5bb.chunk.js", "static/js/[name].[contenthash:8].js"],
  ["/static/js/0.b188e5bb.chunk.js.map", "static/js/[name].[contenthash:8].js"],
  ["/static/js/1.c8bc9647.chunk.js", "static/js/[name].[contenthash:8].js"],
  ["/static/js/1.c8bc9647.chunk.js.map", "static/js/[name].[contenthash:8].js"],
  ["/static/css/client.6ef5c82f.css", "static/css/[name].[contenthash:8].css"],
  ["/static/js/client.5fb812c3.js", "static/js/[name].[contenthash:8].js"],
  ["/static/js/client.5fb812c3.js.map", "static/js/[name].[contenthash:8].js"],
  ["/static/js/3.e1d0e2fa.chunk.js", "static/js/[name].[contenthash:8].js"],
  ["/static/js/3.e1d0e2fa.chunk.js.map", "static/js/[name].[contenthash:8].js"],
  ["/static/js/4.1617d2d8.chunk.js", "static/js/[name].[contenthash:8].js"],
  ["/static/js/4.1617d2d8.chunk.js.map", "static/js/[name].[contenthash:8].js"],
  ["/static/js/5.a7fdfab7.chunk.js", "static/js/[name].[contenthash:8].js"],
  ["/static/js/5.a7fdfab7.chunk.js.map", "static/js/[name].[contenthash:8].js"],
  ["/static/js/6.997a26e3.chunk.js", "static/js/[name].[contenthash:8].js"],
  ["/static/js/6.997a26e3.chunk.js.map", "static/js/[name].[contenthash:8].js"],
  ["/static/js/7.8e1edd37.chunk.js", "static/js/[name].[contenthash:8].js"],
  ["/static/js/7.8e1edd37.chunk.js.map", "static/js/[name].[contenthash:8].js"],
  ["/static/css/client.6ef5c82f.css.map", "static/css/[name].[contenthash:8].css"],
  ["/static/media/AlfaSlabOne-Regular.latin-ext.27a7fa3c.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/AlfaSlabOne-Regular.latin-ext.a4084382.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/AlfaSlabOne-Regular.latin.144929c1.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/AlfaSlabOne-Regular.latin.d94102b5.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/AlfaSlabOne-Regular.vietnamese.98ac915d.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/AlfaSlabOne-Regular.vietnamese.abab182b.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBold.cyrillic-ext.039b9844.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBold.cyrillic-ext.8eecb315.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBold.cyrillic.7cc19799.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBold.cyrillic.cfb0858c.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBold.greek-ext.0825ae6f.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBold.greek-ext.ce717979.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBold.greek.7d1a591c.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBold.greek.e6782b58.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBold.latin-ext.4dfd45e3.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBold.latin-ext.dffdf36f.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBold.latin.4a44ddee.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBold.latin.b840aea6.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBold.vietnamese.4f8068f3.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBold.vietnamese.e00366a5.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBoldItalic.cyrillic-ext.99498f50.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBoldItalic.cyrillic-ext.d03b802e.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBoldItalic.cyrillic.3bcb6058.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBoldItalic.cyrillic.89c6d016.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBoldItalic.greek-ext.9e0dbad1.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBoldItalic.greek-ext.b38e751c.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBoldItalic.greek.917c21a7.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBoldItalic.greek.af8767b7.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBoldItalic.latin-ext.b52ded53.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBoldItalic.latin-ext.f39e75ea.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBoldItalic.latin.6167d8a7.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBoldItalic.latin.fbc1b707.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBoldItalic.vietnamese.68f9ce2c.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-ExtraBoldItalic.vietnamese.b478b98a.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Italic.cyrillic-ext.da133345.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Italic.cyrillic-ext.dd8f212d.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Italic.cyrillic.3f4367f0.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Italic.cyrillic.f1b6af29.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Italic.greek-ext.2bc65aab.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Italic.greek-ext.fa30483b.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Italic.greek.36b1d521.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Italic.greek.69840561.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Italic.latin-ext.a4f1ac1b.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Italic.latin-ext.af6040d9.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Italic.latin.6b675533.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Italic.latin.f3b9ba78.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Italic.vietnamese.c7779833.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Italic.vietnamese.e517bf60.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Regular.cyrillic-ext.6eea9aad.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Regular.cyrillic-ext.8d3b2e2e.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Regular.cyrillic.3199b9e6.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Regular.cyrillic.b3f5b414.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Regular.greek-ext.087b5c18.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Regular.greek-ext.ffccd111.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Regular.greek.55e38915.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Regular.greek.8d58bc1a.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Regular.latin-ext.621f1ab8.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Regular.latin-ext.e42256ec.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Regular.latin.7815d7dd.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Regular.latin.81a5ec8e.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Regular.vietnamese.75539d49.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-Regular.vietnamese.dbf1ed32.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBold.cyrillic-ext.3a22fa80.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBold.cyrillic-ext.a327fd33.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBold.cyrillic.a2f0427d.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBold.cyrillic.a3abda3c.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBold.greek-ext.345fdee3.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBold.greek-ext.e19243ca.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBold.greek.93b1af60.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBold.greek.f129bb59.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBold.latin-ext.3648adb7.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBold.latin-ext.a30ee8e1.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBold.latin.e37f3d66.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBold.latin.ff419753.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBold.vietnamese.76a36fdc.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBold.vietnamese.ee2226d5.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBoldItalic.cyrillic-ext.4bfcc3c6.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBoldItalic.cyrillic-ext.80a17f8a.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBoldItalic.cyrillic.2d48b79d.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBoldItalic.cyrillic.6bacb2d3.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBoldItalic.greek-ext.40efc201.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBoldItalic.greek-ext.8f469dde.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBoldItalic.greek.0883fe3d.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBoldItalic.greek.52450dd2.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBoldItalic.latin-ext.6821bcfb.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBoldItalic.latin-ext.a4a3fe91.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBoldItalic.latin.12300559.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBoldItalic.latin.6d365257.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBoldItalic.vietnamese.43c778c1.woff2", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/FiraSans-SemiBoldItalic.vietnamese.71bdea4a.woff", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/discord.aac89c53.svg", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/ferris-img.407b714e.png", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/github.19432320.svg", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/rust-logo-blk.7129c7d5.svg", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/twitter.23f019eb.svg", "static/media/[name].[contenthash:8].[ext]"],
  ["/static/media/youtube.f750d42f.svg", "static/media/[name].[contenthash:8].[ext]"],
];

describe("Fail", () => {
  for (const [filename, filenameTemplate] of shouldFailFixtures) {
    test(`should detect that ${filenameTemplate} could not generate ${filename}`, () => {
      const matches = fileMatchesTemplate(filename, filenameTemplate);
      expect(matches).toBe(false);
    });
  }
});

describe("Pass", () => {
  for (const [filename, filenameTemplate] of shouldPassFixtures) {
    test(`should detect that ${filenameTemplate} could generate ${filename}`, () => {
      const matches = fileMatchesTemplate(filename, filenameTemplate);
      expect(matches).toBe(true);
    });
  }
});
