apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: web-rust-lang
spec:
  template:
    spec:
      containers:
        - image: ${env:CONTAINER_IMAGE_URL}
          env:
            # Basic
            - name: ENV
              value: ${env:ENV}
